### PR TITLE
apply non-null safety migration

### PR DESCRIPTION
**Pull request by InSomniaMoon**

### CODE REVIEW

**Comment by nkshah2** [comment]
Hi @InSomniaMoon , Thanks for the Pull Request. Since the travis config seems broken currently and fixing it would take more time than I can spare at the moment, do you mind attaching a screenshot of the test results to your PR? Id be happy to merge and release after that

**Comment by nkshah2** [comment]
Hi @InSomniaMoon , I have updated the travis config to fix the build error. Can you update from latest master? Once the test suite passes on your PR ill be happy to merge and release

**Comment by InSomniaMoon** [comment]
Ok, theoretically, I've rebased my master on yours, it should be ok !

**Comment by nkshah2** [comment]
Yep seems to have worked, thanks!

**Comment by nkshah2** [comment]
Version 1.2.0 has been released, should be available on pub once processing is done. Thanks again for the PR @InSomniaMoon !

**Pull request merged**
